export const datas = [
    {
      Image: "https://via.placeholder.com/150",
      Name: "Tech Innovations Inc.",
      field: "Information Technology",
      description: "A leading IT company specializing in software development and cloud solutions.",
      rating: 4.8,
    },
    {
      Image: "https://via.placeholder.com/150",
      Name: "Global FinTech Solutions",
      field: "Finance",
      description: "Offering cutting-edge financial technologies and services globally.",
      rating: 4.5,
    },
    {
      Image: "https://via.placeholder.com/150",
      Name: "Green Earth Engineering",
      field: "Engineering",
      description: "Dedicated to sustainable engineering and renewable energy projects.",
      rating: 4.7,
    },
    {
      Image: "https://via.placeholder.com/150",
      Name: "Creative Media Hub",
      field: "Media & Advertising",
      description: "A creative agency specializing in branding, marketing, and multimedia production.",
      rating: 4.6,
    },
    {
      Image: "https://via.placeholder.com/150",
      Name: "Health Plus Solutions",
      field: "Healthcare",
      description: "Providing innovative health solutions and medical research services.",
      rating: 4.9,
    },
    {
      Image: "https://via.placeholder.com/150",
      Name: "BuildSmart Construction",
      field: "Construction",
      description: "Focused on building smart and sustainable infrastructure for the future.",
      rating: 4.4,
    },
    {
      Image: "https://via.placeholder.com/150",
      Name: "EduTech Academy",
      field: "Education",
      description: "Empowering students with advanced e-learning platforms and tools.",
      rating: 4.8,
    },
    {
      Image: "https://via.placeholder.com/150",
      Name: "EcomXperts",
      field: "E-commerce",
      description: "Specialists in e-commerce strategy, logistics, and digital transformation.",
      rating: 4.3,
    },
    {
      Image: "https://via.placeholder.com/150",
      Name: "Future Mobility Solutions",
      field: "Automotive",
      description: "Pioneering the future of electric and autonomous vehicles.",
      rating: 4.6,
    },
    {
      Image: "https://via.placeholder.com/150",
      Name: "Urban Living Architects",
      field: "Architecture",
      description: "Designing modern, functional, and aesthetic urban spaces.",
      rating: 4.7,
    },
  ];